### ISSUE TITLE
Calculation of corner latitudes

### ISSUE THREAD

**Issue by uwefladrich** [JanStreffing/ocp-tool#5] opened 2021-03-23 20:28 UTC
Hi,
I can't really get my head around the calculation of corner latitudes in `calculate_corner_latlon`. I understand that for each latitude band, the difference in latitude between the center and the cell edges are calculated. Lets take the northwards difference, which is in the regular case:
```
dlat_n = (lat_list[ii-1] - lat) / 2.
```
I understand it such that the cell edge is in the middle between two centers, which makes sense to me. But when `dlat_n` is used to compute the latitude of northwards corners (i.e. latitude of the cell edge), it is divided by two again:
```
 # corner 1: north-east
[...]
crn_lats[0, 0, kk] = lat + dlat_n/2.
```
Isn't that one division by 2 too much? Or am I missing/misunderstanding something?

**Comment by uwefladrich** [comment] 2021-03-25 07:41
Hi @etiennesky ,
Do you think that this issue could be related to what you mentioned recently about the grids created by the ocp-tool? You also mentioned something that could turn `grids.nc` into shape files, if I understood correctly. What was that exactly?

**Comment by etiennesky** [comment] 2021-04-09 11:52
Hi @uwefladrich sorry for not replying earlier, I didn't see the notification and just saw this issue as I was going to open a new one...

I can confirm this is the same problem I encountered, with the T255 grid the latitudinal spacing between grid corners is about 0.35 or half of what it should be (about 0.7). This was found by a collaborator when making a shapefile of the land points 

I can also confirm that removing the second division by 2. solves the problem.

To illustrate this here are some variables for 3 points (north pole, equator, south pole) which represent :

lon, lat, IFSindex, index, area, cornerla[0], cornerla[1], cornerla[2], cornerla[3], cornerlo[0], cornerlo[1], cornerlo[2], cornerlo[3], difflat, difflon, lsmask

the important values are the corners and differences (diffla/difflo), the point at the equator has lon and lat spacing of 0.70 
```
 0.00000	89.46282	1	0	1690052736.00000	90.00000	90.00000	89.11489	89.11489	10.00000	-10.00000	-10.00000	10.00000	-0.88511	-20.00000	 0.00000
 0.00000	-0.35088	44420	44419	6098732544.00000	 0.00000	 0.00000	-0.70175	-0.70175	 0.35156	-0.35156	-0.35156	 0.35156	-0.70175	-0.70312	 0.00000
-20.00000	-89.46282	88838	88837	1690052736.00000	-89.11489	-89.11489	-90.00000	-90.00000	-10.00000	-30.00000	-30.00000	-10.00000	-0.88511	-20.00000	 1.00000
```
and the same points without the fix, the point on the equator has a lat spacing of 0.35
```
  0.00000	89.46282	1	0	1690052736.00000	89.73141	89.73141	89.28885	89.28885	10.00000	-10.00000	-10.00000	10.00000	-0.44256	-20.00000	 0.00000
0.00000	-0.35088	44420	44419	6098732544.00000	-0.17544	-0.17544	-0.52632	-0.52632	 0.35156	-0.35156	-0.35156	 0.35156	-0.35088	-0.70312	 0.00000
-20.00000	-89.46282	88838	88837	1690052736.00000	-89.28885	-89.28885	-89.73141	-89.73141	-10.00000	-30.00000	-30.00000	-10.00000	-0.44256	-20.00000	 1.00000
```

I will send the modified data to the collaborator to confirm that this fix is fine and make a MR.

**Comment by uwefladrich** [comment] 2021-04-12 06:56
Great, thanks!
(I get drowned in Github notifications as well, sometimes missing the important ones.)

**Comment by etiennesky** [comment] 2021-04-15 17:41
I can confirm that the fix works as intended, should I submit a MR?

Here is the diff

```
--- ocp-tool.py.mod2    2021-04-15 19:40:22.599200225 +0200
+++ ocp-tool.py.mod3    2021-04-15 19:40:22.153398976 +0200
@@ -283,21 +283,21 @@
             dlat_s = (lat - lat_list[ii+1]) / 2.
 
         for jj in range(ni):
-        # corner 1: north-east
+            # corner 1: north-east
             crn_lons[0, 0, kk] = lons[jj] + dlon/2.
-            crn_lats[0, 0, kk] = lat + dlat_n/2.
+            crn_lats[0, 0, kk] = lat + dlat_n
 
-        # corner 2: north-west
+            # corner 2: north-west
             crn_lons[1, 0, kk] = lons[jj] - dlon/2.
-            crn_lats[1, 0, kk] = lat + dlat_n/2.
+            crn_lats[1, 0, kk] = lat + dlat_n
 
-        # corner 3: south-west
+            # corner 3: south-west
             crn_lons[2, 0, kk] = lons[jj] - dlon/2.
-            crn_lats[2, 0, kk] = lat - dlat_s/2.
+            crn_lats[2, 0, kk] = lat - dlat_s
 
-        # corner 4: south-east
+            # corner 4: south-east
             crn_lons[3, 0, kk] = lons[jj] + dlon/2.
-            crn_lats[3, 0, kk] = lat - dlat_s/2.
+            crn_lats[3, 0, kk] = lat - dlat_s
 
             kk += 1
 
```

**Comment by JanStreffing** [comment] 2021-09-05 19:11
Hey @etiennesky Somehow I also did not get any notification for this. I just stumbled across this error myself. I have merged by hand. Ty for the contribution!

**Closed by JanStreffing** 2021-09-05 19:11 UTC
